#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Dynamically run with available python interpreter
if command -v py &> /dev/null; then
    py "$DIR/mock_hpe_cli.py" shownode "$@"
elif command -v python3 &> /dev/null; then
    python3 "$DIR/mock_hpe_cli.py" shownode "$@"
else
    python "$DIR/mock_hpe_cli.py" shownode "$@"
fi
